#!/usr/bin/env python3
"""
generate_area_codes.py — Genera JSONs de códigos de área regionales
por país en static/data/area_codes/{CC}.json.

Los nombres de región deben coincidir EXACTO con los de
admin1CodesASCII.txt (usados en los archivos de ciudades).

Uso:
    python scripts/generate_area_codes.py
"""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(PROJECT_DIR, "static", "data", "area_codes")

# ═══════════════════════════════════════════════════════════════════
# Datos de códigos de área por país.
# Clave = nombre EXACTO de admin1 en GeoNames, Valor = código de área.
# ═══════════════════════════════════════════════════════════════════

AREA_CODES = {

    # ── LATINOAMÉRICA ──────────────────────────────────────────────

    "CO": {
        "Bogota D.C.": "601",
        "Antioquia": "604",
        "Chocó": "604",
        "Valle del Cauca Department": "602",
        "Cauca Department": "602",
        "Nariño": "602",
        "Atlántico": "605",
        "Bolívar": "605",
        "Cesar Department": "605",
        "Córdoba": "605",
        "La Guajira Department": "605",
        "Magdalena Department": "605",
        "Sucre Department": "605",
        "Caldas Department": "606",
        "Quindío Department": "606",
        "Risaralda Department": "606",
        "Santander Department": "607",
        "Norte de Santander Department": "607",
        "Arauca Department": "607",
        "Boyacá": "608",
        "Casanare Department": "608",
        "Cundinamarca": "608",
        "Meta Department": "608",
        "Amazonas Department": "608",
        "Caquetá": "608",
        "Guainía Department": "608",
        "Guaviare Department": "608",
        "Huila Department": "608",
        "Putumayo Department": "608",
        "Tolima Department": "608",
        "Vaupés": "608",
        "Vichada Department": "608",
        "San Andres y Providencia": "608",
    },

    "MX": {
        "Mexico City": "55",
        "Jalisco": "33",
        "Nuevo León": "81",
        "Puebla": "222",
        "Guanajuato": "477",
        "Chihuahua": "614",
        "Baja California": "664",
        "Sonora": "662",
        "Coahuila": "844",
        "Tamaulipas": "834",
        "Veracruz": "229",
        "Oaxaca": "951",
        "Guerrero": "747",
        "Michoacán": "443",
        "Sinaloa": "667",
        "Querétaro": "442",
        "San Luis Potosí": "444",
        "Hidalgo": "771",
        "Tabasco": "993",
        "Yucatán": "999",
        "Quintana Roo": "998",
        "Aguascalientes": "449",
        "Morelos": "777",
        "Durango": "618",
        "Zacatecas": "492",
        "Colima": "312",
        "Nayarit": "311",
        "Tlaxcala": "246",
        "Campeche": "981",
        "Baja California Sur": "612",
        "Chiapas": "961",
        "México": "722",
    },

    "AR": {
        "Buenos Aires F.D.": "11",
        "Buenos Aires": "221",
        "Cordoba": "351",
        "Santa Fe": "342",
        "Mendoza": "261",
        "Tucuman": "381",
        "Entre Rios": "343",
        "Salta": "387",
        "Misiones": "376",
        "Chaco": "362",
        "Corrientes": "379",
        "Santiago del Estero": "385",
        "San Juan": "264",
        "Jujuy": "388",
        "Rio Negro": "2920",
        "Neuquen": "299",
        "Formosa": "370",
        "Chubut": "2965",
        "San Luis": "266",
        "Catamarca": "383",
        "La Rioja": "380",
        "La Pampa": "2954",
        "Santa Cruz": "2966",
        "Tierra del Fuego": "2901",
    },

    "BR": {
        "São Paulo": "11",
        "Rio de Janeiro": "21",
        "Minas Gerais": "31",
        "Bahia": "71",
        "Rio Grande do Sul": "51",
        "Paraná": "41",
        "Pernambuco": "81",
        "Ceará": "85",
        "Federal District": "61",
        "Pará": "91",
        "Maranhão": "98",
        "Goiás": "62",
        "Santa Catarina": "48",
        "Amazonas": "92",
        "Espírito Santo": "27",
        "Paraíba": "83",
        "Rio Grande do Norte": "84",
        "Alagoas": "82",
        "Piauí": "86",
        "Mato Grosso": "65",
        "Mato Grosso do Sul": "67",
        "Sergipe": "79",
        "Rondônia": "69",
        "Tocantins": "63",
        "Acre": "68",
        "Amapá": "96",
        "Roraima": "95",
    },

    "CL": {
        "Santiago Metropolitan": "2",
        "Valparaíso": "32",
        "Biobío": "41",
        "Araucanía": "45",
        "Los Lagos Region": "65",
        "Maule Region": "71",
        "O'Higgins Region": "72",
        "Coquimbo Region": "51",
        "Antofagasta": "55",
        "Atacama": "52",
        "Tarapacá": "57",
        "Arica y Parinacota Region": "58",
        "Aysén": "67",
        "Region of Magallanes": "61",
        "Los Ríos Region": "63",
        "Ñuble": "42",
    },

    "PE": {
        "Lima Province": "1",
        "Lima region": "1",
        "Callao": "1",
        "Arequipa": "54",
        "La Libertad": "44",
        "Lambayeque": "74",
        "Piura": "73",
        "Cuzco Department": "84",
        "Junin": "64",
        "Ancash": "43",
        "Cajamarca Department": "76",
        "Ica": "56",
        "Puno": "51",
        "Huánuco Department": "62",
        "Loreto": "65",
        "San Martín Department": "42",
        "Tacna": "52",
        "Ucayali": "61",
        "Ayacucho": "66",
        "Amazonas": "41",
        "Apurímac Department": "83",
        "Huancavelica": "67",
        "Madre de Dios": "82",
        "Moquegua Department": "53",
        "Pasco": "63",
        "Tumbes": "72",
    },

    "EC": {
        "Pichincha": "2",
        "Guayas": "4",
        "Azuay": "7",
        "Manabí": "5",
        "El Oro": "7",
        "Tungurahua Province": "3",
        "Loja": "7",
        "Chimborazo Province": "3",
        "Imbabura": "6",
        "Cotopaxi": "3",
        "Los Ríos": "5",
        "Esmeraldas": "6",
        "Bolívar": "3",
        "Carchi": "6",
        "Cañar": "7",
        "Santa Elena": "4",
        "Santo Domingo de los Tsáchilas": "2",
        "Sucumbíos": "6",
        "Orellana Province": "6",
        "Napo": "6",
        "Pastaza Province": "3",
        "Morona-Santiago Province": "7",
        "Zamora Chinchipe": "7",
        "Galápagos": "5",
    },

    "VE": {
        "Distrito Federal": "212",
        "Miranda": "212",
        "Vargas": "212",
        "Zulia": "261",
        "Carabobo": "241",
        "Lara": "251",
        "Aragua": "243",
        "Bolívar": "285",
        "Anzoátegui": "281",
        "Táchira": "276",
        "Mérida": "274",
        "Falcón": "268",
        "Monagas": "291",
        "Sucre": "293",
        "Portuguesa": "255",
        "Barinas": "273",
        "Trujillo": "271",
        "Guárico": "246",
        "Nueva Esparta": "295",
        "Yaracuy": "254",
        "Apure": "247",
        "Cojedes": "258",
        "Delta Amacuro": "287",
        "Amazonas": "248",
    },

    "BO": {
        "La Paz Department": "2",
        "Santa Cruz Department": "3",
        "Cochabamba": "4",
        "Oruro": "52",
        "Potosí Department": "62",
        "Chuquisaca Department": "64",
        "Tarija Department": "66",
        "Beni Department": "3",
        "Pando": "3",
    },

    "PY": {
        "Asunción": "21",
        "Central Department": "21",
        "Alto Paraná Department": "61",
        "Itapúa": "71",
        "Caaguazú Department": "522",
        "San Pedro Department": "342",
        "Amambay Department": "336",
        "Concepción": "331",
        "Cordillera Department": "25",
        "Guairá": "541",
        "Paraguarí": "531",
        "Misiones Department": "81",
        "Ñeembucú Department": "81",
        "Caazapá": "542",
        "Canindeyú": "46",
        "Alto Paraguay": "36",
        "Presidente Hayes": "92",
        "Boquerón Department": "91",
    },

    "UY": {
        "Montevideo Department": "2",
        "Canelones": "2",
        "Maldonado": "42",
        "Salto Department": "73",
        "Paysandú Department": "72",
        "Rivera Department": "62",
        "Colonia": "52",
        "Soriano": "532",
        "Cerro Largo": "642",
        "Artigas": "772",
        "Rocha Department": "447",
        "Flores Department": "536",
        "Florida": "352",
        "Lavalleja": "442",
        "Durazno Department": "362",
        "San José Department": "342",
        "Río Negro Department": "567",
        "Tacuarembó Department": "632",
        "Treinta y Tres Department": "452",
    },

    "CU": {
        "Havana": "7",
        "Santiago de Cuba Province": "22",
        "Camagüey": "32",
        "Holguín Province": "24",
        "Matanzas Province": "45",
        "Villa Clara Province": "42",
        "Granma Province": "23",
        "Cienfuegos Province": "43",
        "Pinar del Río": "48",
        "Sancti Spíritus Province": "41",
        "Las Tunas Province": "31",
        "Guantánamo Province": "21",
        "Ciego de Ávila Province": "33",
        "Artemisa": "47",
        "Mayabeque": "47",
        "Isla de la Juventud": "46",
    },

    # ── EUROPA ─────────────────────────────────────────────────────

    "ES": {
        "Madrid": "91",
        "Catalonia": "93",
        "Andalusia": "95",
        "Valencia": "96",
        "Galicia": "981",
        "Basque Country": "94",
        "Castille and León": "983",
        "Castille-La Mancha": "925",
        "Canary Islands": "928",
        "Aragon": "976",
        "Asturias": "985",
        "Extremadura": "924",
        "Balearic Islands": "971",
        "Murcia": "968",
        "Navarre": "948",
        "Cantabria": "942",
        "La Rioja": "941",
        "Ceuta": "956",
        "Melilla": "952",
    },

    "FR": {
        "Île-de-France": "1",
        "Provence-Alpes-Côte d'Azur": "4",
        "Rhône-Alpes": "4",
        "Nouvelle-Aquitaine": "5",
        "Occitanie": "5",
        "Hauts-de-France": "3",
        "Grand Est": "3",
        "Brittany": "2",
        "Normandy": "2",
        "Pays de la Loire": "2",
        "Centre-Val de Loire": "2",
        "Bourgogne": "3",
        "Corsica": "4",
    },

    "DE": {
        "State of Berlin": "30",
        "Hamburg": "40",
        "Bavaria": "89",
        "North Rhine-Westphalia": "211",
        "Baden-Wurttemberg": "711",
        "Hesse": "69",
        "Lower Saxony": "511",
        "Saxony": "351",
        "Schleswig-Holstein": "431",
        "Brandenburg": "331",
        "Thuringia": "361",
        "Rheinland-Pfalz": "6131",
        "Saarland": "681",
        "Saxony-Anhalt": "391",
        "Mecklenburg-Vorpommern": "381",
        "City state Bremen": "421",
    },

    "IT": {
        "Lazio": "06",
        "Lombardy": "02",
        "Campania": "081",
        "Veneto": "041",
        "Piedmont": "011",
        "Emilia-Romagna": "051",
        "Sicily": "091",
        "Tuscany": "055",
        "Apulia": "080",
        "Liguria": "010",
        "Calabria": "0961",
        "Sardinia": "070",
        "The Marches": "071",
        "Friuli Venezia Giulia": "040",
        "Abruzzo": "085",
        "Umbria": "075",
        "Trentino-Alto Adige": "0461",
        "Basilicate": "0971",
        "Molise": "0874",
        "Aosta Valley": "0165",
    },

    "PT": {
        "Lisbon": "21",
        "Porto": "22",
        "Braga": "253",
        "Aveiro": "234",
        "Coimbra": "239",
        "Setúbal": "265",
        "Faro": "289",
        "Leiria": "244",
        "Santarém": "243",
        "Viseu": "232",
        "Viana do Castelo": "258",
        "Vila Real": "259",
        "Bragança": "273",
        "Guarda": "271",
        "Castelo Branco": "272",
        "Portalegre": "245",
        "Évora": "266",
        "Beja": "284",
        "Madeira": "291",
        "Azores": "296",
    },

    "GB": {
        "England": "20",
        "Scotland": "131",
        "Wales": "29",
        "Northern Ireland": "28",
    },

    # ── NORTEAMÉRICA ───────────────────────────────────────────────

    "US": {
        "Alabama": "205",
        "Alaska": "907",
        "Arizona": "602",
        "Arkansas": "501",
        "California": "213",
        "Colorado": "303",
        "Connecticut": "203",
        "Delaware": "302",
        "District of Columbia": "202",
        "Florida": "305",
        "Georgia": "404",
        "Hawaii": "808",
        "Idaho": "208",
        "Illinois": "312",
        "Indiana": "317",
        "Iowa": "515",
        "Kansas": "316",
        "Kentucky": "502",
        "Louisiana": "504",
        "Maine": "207",
        "Maryland": "301",
        "Massachusetts": "617",
        "Michigan": "313",
        "Minnesota": "612",
        "Mississippi": "601",
        "Missouri": "314",
        "Montana": "406",
        "Nebraska": "402",
        "Nevada": "702",
        "New Hampshire": "603",
        "New Jersey": "201",
        "New Mexico": "505",
        "New York": "212",
        "North Carolina": "704",
        "North Dakota": "701",
        "Ohio": "216",
        "Oklahoma": "405",
        "Oregon": "503",
        "Pennsylvania": "215",
        "Rhode Island": "401",
        "South Carolina": "803",
        "South Dakota": "605",
        "Tennessee": "615",
        "Texas": "214",
        "Utah": "801",
        "Vermont": "802",
        "Virginia": "804",
        "Washington": "206",
        "West Virginia": "304",
        "Wisconsin": "414",
        "Wyoming": "307",
    },

    "CA": {
        "Ontario": "416",
        "Quebec": "514",
        "British Columbia": "604",
        "Alberta": "403",
        "Manitoba": "204",
        "Saskatchewan": "306",
        "Nova Scotia": "902",
        "New Brunswick": "506",
        "Newfoundland and Labrador": "709",
        "Prince Edward Island": "902",
        "Northwest Territories": "867",
        "Nunavut": "867",
        "Yukon": "867",
    },
}


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for cc, mapping in sorted(AREA_CODES.items()):
        path = os.path.join(OUTPUT_DIR, f"{cc}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(mapping, f, ensure_ascii=False, indent=2)

    print(f"Generados {len(AREA_CODES)} archivos en {OUTPUT_DIR}")
    total_regions = sum(len(v) for v in AREA_CODES.values())
    print(f"Total regiones mapeadas: {total_regions}")


if __name__ == "__main__":
    main()
